# Azure DevOps Pipeline for Document Intelligence Model Promotion
# This pipeline promotes Azure Document Intelligence models from Dev -> QA -> Prod environments
# Updated to use PowerShell scripts for improved reliability and Windows compatibility

trigger:
  branches:
    include:
    - main
    - develop
  paths:
    include:
    - models/*
    - scripts/*
    - azure-pipelines.yml

variables:
  # Global variables
  - name: azureServiceConnection
    value: 'azure-service-connection' # Update with your service connection name
  - name: modelName
    value: 'SampleInvoices-1.0'
  - name: modelVersion
    value: '$(Build.BuildNumber)'
  
  # Environment-specific variable groups
  - group: 'doc-intelligence-dev'
  - group: 'doc-intelligence-qa' 
  - group: 'doc-intelligence-prod'

stages:
- stage: PromoteToQA
  displayName: 'Promote to QA Environment'
  jobs:
  - deployment: DeployToQA
    displayName: 'Deploy Model to QA'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'QA'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzurePowerShell@5
            displayName: 'Copy Model to QA Environment'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/s/scripts/Copy-Model.ps1'
              ScriptArguments: '-SourceService "$(DEV_COGNITIVE_SERVICE_NAME)" -TargetService "$(QA_COGNITIVE_SERVICE_NAME)" -ModelName "$(modelName)" -SourceResourceGroup "$(DEV_RESOURCE_GROUP)" -TargetResourceGroup "$(QA_RESOURCE_GROUP)"'
              azurePowerShellVersion: 'LatestVersion'
              # Uses PowerShell script that follows Microsoft's recommended Document Intelligence model copy API

          - task: AzurePowerShell@5
            displayName: 'Test Model in QA'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/s/scripts/test-model.ps1'
              ScriptArguments: '-CognitiveServiceName "$(QA_COGNITIVE_SERVICE_NAME)" -ModelName "$(modelName)" -Environment "qa" -ResourceGroup "$(QA_RESOURCE_GROUP)"'
              azurePowerShellVersion: 'LatestVersion'

- stage: PromoteToProd
  displayName: 'Promote to Production Environment'
  dependsOn: PromoteToQA
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployToProd
    displayName: 'Deploy Model to Production'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: 'Backup Current Production Model'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Backup current production model
                ./scripts/backup-model.sh $(PROD_COGNITIVE_SERVICE_NAME) $(modelName) $(PROD_RESOURCE_GROUP)

          - task: AzurePowerShell@5
            displayName: 'Copy Model to Production'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/s/scripts/Copy-Model.ps1'
              ScriptArguments: '-SourceService "$(QA_COGNITIVE_SERVICE_NAME)" -TargetService "$(PROD_COGNITIVE_SERVICE_NAME)" -ModelName "$(modelName)" -SourceResourceGroup "$(QA_RESOURCE_GROUP)" -TargetResourceGroup "$(PROD_RESOURCE_GROUP)"'
              azurePowerShellVersion: 'LatestVersion'
              # Uses PowerShell script with automatic target model deletion before copy

          - task: AzurePowerShell@5
            displayName: 'Smoke Test Production Model'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              ScriptType: 'FilePath'
              ScriptPath: '$(Pipeline.Workspace)/s/scripts/test-model.ps1'
              ScriptArguments: '-CognitiveServiceName "$(PROD_COGNITIVE_SERVICE_NAME)" -ModelName "$(modelName)" -Environment "prod" -ResourceGroup "$(PROD_RESOURCE_GROUP)" -SmokeTestOnly'
              azurePowerShellVersion: 'LatestVersion'
